name = "TestJiveRunMoreTests"
uuid = "a90e1516-e118-4dbd-8025-f563350fc7d4"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[compat]
Jive = "0.3"
ANSIColoredPrinters = "0.0"
Aqua = "0.8, 1.0"
TestItems = "1.0"
TestItemRunner = "1.1"
SafeTestsets = "0.1"
TestRunner = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
ANSIColoredPrinters = "a4c015fc-c6ff-483c-b24f-f7ea428134e9"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
TestRunner = "4efbe77e-ddf3-4ce7-be91-16409ca9e85f"

[targets]
test = ["Test", "Jive", "ANSIColoredPrinters", "Aqua", "TestItems", "TestItemRunner", "SafeTestsets", "TestRunner"]
